### ISSUE TITLE
Can't import module in Angular 2 V4 (CLI)

### ISSUE THREAD

**Issue by gusseleet** [umens/ngx-magicsearch#32]
I tried to import the module like this:

import { NgxMagicSearchBarModule } from 'ngx-magicsearch';

But the module has no exporting member with that name. 
I tried added the index file to scripts in angular-cli.json, but that did not help.

**Comment by umens** [comment]
Hi @gusseleet. It's a typo in the README. Change NgxMagicSearchBarModule by NgxMagicSearchModule and it should be better. I need to fix the readme.
Thanx for using the lib btw

**Comment by umens** [comment]
Fix the typo in commit  51b9bde2521236a5538b3e8e942237eff94ffdb3
I'm closing this issue.
